services:
  realsense_ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      #target: librealsense
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - /sys/bus/usb:/sys/bus/usb
      - /sys/bus/platform:/sys/bus/platform
      - /dev:/dev
      - /run/udev:/run/udev:ro
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
      - 'c 209:* rmw'
